export const constants = {
    //Auth Actions
    REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
    REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
    REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

    LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
    LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

    LOGOUT: "USERS_LOGOUT",


    //User Actions
    USERS_GETALL_REQUEST: "USERS_GETALL_REQUEST",
    USERS_GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
    USERS_GETALL_FAILURE: "USERS_GETALL_FAILURE",

    UPDATE_PROFILE_PICTURE_REQUEST: "UPDATE_PROFILE_PICTURE_REQUEST",
    UPDATE_PROFILE_PICTURE_SUCCESS: "UPDATE_PROFILE_PICTURE_SUCCESS",
    UPDATE_PROFILE_PICTURE_FAILURE: "UPDATE_PROFILE_PICTURE_FAILURE",

    
    //Post Actions
    POSTS_GETALL_REQUEST: "POSTS_GETALL_REQUEST",
    POSTS_GETALL_SUCCESS: "POSTS_GETALL_SUCCESS",
    POSTS_GETALL_FAILURE: "POSTS_GETALL_FAILURE",

};