/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:35e1ba19-c497-402a-b756-9ed861a46a6d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wtvhAUuZd",
    "aws_user_pools_web_client_id": "3n83ru2m0pkve94o6t822k9gk9",
    "oauth": {},
    "aws_user_files_s3_bucket": "tangau183748-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
